name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Hugging Face Hub
        run: pip install huggingface_hub
          
      - name: Upload to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python << 'EOF'
          from huggingface_hub import HfApi
          import os
          
          api = HfApi(token=os.environ['HF_TOKEN'])
          
          api.upload_folder(
              folder_path=".",
              repo_id="pray/face_matching_mvp",
              repo_type="space",
              commit_message="Update from GitHub Actions",
              ignore_patterns=[
                  ".git/*",
                  ".github/*",
                  "*.pyc",
                  "__pycache__/*",
                  ".gitattributes",
                  ".gitignore",
                  "tests/*",              # Exclude tests from Space
                  "requirements-dev.txt", # Exclude dev dependencies
                  ".pytest_cache/*",
                  "*.egg-info/*",
                  "*.gif",
              ]
          )
          
          print("Upload complete!")
          EOF
